name: First comment in new pull request

on:
  pull_request_target:
    types: [opened]

jobs:
  commentCreated:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    environment: action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: first comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for contributing with [awesome-vpn](https://github.com/dutchakdev/awesome-vpn), we will revise your contribution as soon as possible.
            
            Make sure you add the links in the body of the pull request that are requested in the [contribution guide](https://github.com/dutchakdev/awesome-vpn/blob/main/CONTRIBUTING.md):
            
            > your project is about to be approved, it's under revision, it may take a few days