---
name: Check markdown links
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: articulate/actions-markdownlint@v1
        with:
          config: markdownlint-config.json
          files: '*.md'
          ignore: node_modules
          version: 0.28.1