---
name: Lint markdown
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

permissions:
  issues: write

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run link check (main branch)
        uses: dutchakdev/markdown-links-action@master
        with:
          check-modified-files-only: 'yes'
          base-branch: main
          create-issue: 'yes'
          gh-assignees: 'dutchakdev'
          gh-labels: 'broken-links'
        env:
          GITHUB_TOKEN: ${{ github.token }}
  lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -g markdownlint-cli

      - name: Run Markdown Lint
        run: markdownlint .